[package]
authors = ["Marcel Guzik <mguzik555@gmail.com>"]
edition = "2018"
name = "neomason-discord-bot"
version = "0.1.0"
[dependencies]
dotenv = "0.15.0"
env_logger = "*"
rusqlite = "0.23.1"
regex = "1.3.9"
fancy-regex = "0.3.5"
serenity = "0.8.6"
log = "0.4.8"
chrono = "0.4.19"

[dependencies.refinery]
features = ["rusqlite"]
otenv = "0.15.0"
version = "0.3"

[dependencies.refinery.refinery]
features = ["rusqlite"]
version = "0.3"
