name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Build release binary
        run: cargo build --release
      - name: Import the SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          eval $(ssh-agent -s)
          ssh-agent bash
            ssh-add <(echo "$SSH_KEY")
            mkdir ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
            ssh-add -l
            scp target/release/neomason-discord-bot neomason-bot@mguzik.pl:neomason-$(date +"%FT%T")
            ssh neomason-bot@mguzik.pl ~/run.sh
